# Generated by Django 4.2 on 2023-04-23 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mercado', '0002_alter_produto_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_reg',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='data registro'),
        ),
        migrations.AddField(
            model_name='produto',
            name='prod_desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
