# Generated by Django 4.2 on 2023-04-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mercado', '0003_produto_data_reg_produto_prod_desc_produto_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_reg',
            field=models.DateTimeField(verbose_name='data registro'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='prod_desc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
